const jCategory = [
    {
        index : 0,
        image: "../images/google.png",
        title: "Web Developer",
        rate: '$900-1200/m',
        av: "Full Time",
        companyName: "Google",
        location: "USA",
        vacency: "01 Vacency",
        hours: "50h / week",
        description: "Google is seeking a talented and motivated Web Developer to join our dynamic team. As a Web Developer at Google, you will play a key role in building and maintaining high-quality, responsive websites and web applications. You will collaborate with designers, product managers, and other developers to create innovative solutions that enhance the user experience and drive business success.",
        workplace: "Work from home",
        education: "Bachelor degree in any Computer science Course",
        experience: "2 to 5 year(s)"
    },
    {
        index : 1,
        image: "../images/uber.png",
        title: "Freelancer",
        rate: '$900-1200/m',
        av: "Freelancer",
        companyName: "Uber",
        location: "USA",
        vacency: "04",
        hours: "40h / week",
        description: "At Uber, we are revolutionizing urban transportation and creating a more connected world. As a Driver Partner, you have the freedom to work on your own schedule and be your own boss. You’ll provide safe, reliable, and convenient rides to passengers, contributing to seamless urban mobility. Enjoy competitive earnings, access to exclusive rewards, and support from a dedicated community of drivers. Embrace the opportunity to make a difference in your city, meet new people, and drive with purpose. At Uber, your journey is just as important as your destination. Apply now to become part of our innovative team and drive the future of transportation.",
        workplace: "Work from office",
        education: "Degree in any Computer Science Course.",
        experience: "1 to 5 year(s)",
    },
    {
        index : 2,
        image: "../images/linkedin.png",
        title: "Business Associate",
        rate: '$900-1200/m',
        av: "Part Time",
        companyName: "Linkedin",
        location: "Uk",
        vacency: "08",
        hours: "45h / week",
        description: "Be a part of LinkedIn, the world’s largest professional network, and help us empower professionals to achieve their career goals. As a team member, you will contribute to building innovative solutions that connect people and create economic opportunities for everyone. You’ll work in a collaborative and inclusive environment, driven by a commitment to excellence and continuous learning. With a focus on user experience, technology, and community impact, LinkedIn offers a chance to make a meaningful difference. Embrace the opportunity to grow both personally and professionally while shaping the future of professional networking. Join us and be a catalyst for change in the professional world.",
        workplace: "Work from office",
        education: "Degree in any Computer Science Course.",
        experience: "3 to 5 year(s)",
    },
    {
        index : 3,
        image: "../images/facebook.png",
        title: "Digital Marketing",
        rate: '$800-1000/m',
        av: "Part Time",
        companyName: "Facebook",
        location: "India",
        vacency: "34",
        hours: "52h / week",
        description: "Become a part of Facebook’s mission to give people the power to build community and bring the world closer together. As a team member, you’ll work on groundbreaking projects that shape how billions of people connect, share, and communicate. You'll collaborate with talented individuals in an inclusive, innovative environment that fosters creativity and growth. At Facebook, you'll have the opportunity to make a global impact by developing products that drive social connections and enhance user experiences. Join us and contribute to a platform that’s transforming the digital landscape and empowering people worldwide. Together, we can build a more connected world.",
        workplace: "Work from office",
        education: "Master's Degree in any Computer Science Course.",
        experience: "3 to 6 year(s)",
    },
    {
        index : 4,
        image: "../images/yahoo.png",
        title: "User Experience",
        rate: '$900-1600/m',
        av: "Full Time",
        companyName: "Yahoo",
        location: "India",
        vacency: "34",
        hours: "52h / week",
        description: "Become a part of Yahoo mission to give people the power to build community and bring the world closer together. As a team member, you’ll work on groundbreaking projects that shape how billions of people connect, share, and communicate. You'll collaborate with talented individuals in an inclusive, innovative environment that fosters creativity and growth. At Facebook, you'll have the opportunity to make a global impact by developing products that drive social connections and enhance user experiences. Join us and contribute to a platform that’s transforming the digital landscape and empowering people worldwide. Together, we can build a more connected world.",
        workplace: "Work from office",
        education: "Bachelors's Degree in any Computer Science Course.",
        experience: "3 to 6 year(s)",
    },
    {
        index : 5,
        image: "../images/apple.png",
        title: "Web Developer",
        rate: '$1900-2500/m',
        av: "Full Time",
        companyName: "Apple",
        location: "USA",
        vacency: "04",
        hours: "58h / week",
        description: "Become a part of Apple mission to give people the power to build community and bring the world closer together. As a team member, you’ll work on groundbreaking projects that shape how billions of people connect, share, and communicate. You'll collaborate with talented individuals in an inclusive, innovative environment that fosters creativity and growth. At Facebook, you'll have the opportunity to make a global impact by developing products that drive social connections and enhance user experiences. Join us and contribute to a platform that’s transforming the digital landscape and empowering people worldwide. Together, we can build a more connected world.",
        workplace: "Work from office",
        education: "Bachelors's Degree in any Computer Science Course.",
        experience: "3 to 6 year(s)",
    },
    {
        index : 6,
        image: "../images/instagram.png",
        title: "Product Designer",
        rate: '$1100-2000/m',
        av: "Full Time",
        companyName: "Instagram",
        location: "USA",
        vacency: "09",
        hours: "48h / week",
        description: "Become a part of Instagram mission to give people the power to build community and bring the world closer together. As a team member, you’ll work on groundbreaking projects that shape how billions of people connect, share, and communicate. You'll collaborate with talented individuals in an inclusive, innovative environment that fosters creativity and growth. At Facebook, you'll have the opportunity to make a global impact by developing products that drive social connections and enhance user experiences. Join us and contribute to a platform that’s transforming the digital landscape and empowering people worldwide. Together, we can build a more connected world.",
        workplace: "Work from office",
        education: "Bachelors's Degree in any Computer Science Course.",
        experience: "3 to 6 year(s)",
    },
    {
        index : 7,
        image: "../images/wordpress.png",
        title: "Freelancer",
        rate: '$1100-2000/m',
        av: "Part Time",
        companyName: "Word Press",
        location: "USA",
        vacency: "11",
        hours: "38h / week",
        description: "Become a part of WordPress mission to give people the power to build community and bring the world closer together. As a team member, you’ll work on groundbreaking projects that shape how billions of people connect, share, and communicate. You'll collaborate with talented individuals in an inclusive, innovative environment that fosters creativity and growth. At Facebook, you'll have the opportunity to make a global impact by developing products that drive social connections and enhance user experiences. Join us and contribute to a platform that’s transforming the digital landscape and empowering people worldwide. Together, we can build a more connected world.",
        workplace: "Work from office",
        education: "Bachelors's Degree in any Computer Science Course.",
        experience: "3 to 6 year(s)",
    },
]